FROM ruby:2.1.10

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nodejs \
    sqlite3 \
    libsqlite3-dev

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
RUN rake db:migrate

CMD rails s -p 3000
